In [1]:
import tensorflow as tf
print(('Your TensorFlow version: {0}').format(tf.__version__))

Your TensorFlow version: 2.9.1


In [2]:
# Create a constant tensor A
A = tf.constant([[4, 3],
                 [6, 1]])

In [3]:
# Create a Variable tensor A
V = tf.Variable([[3, 1],
                 [5, 2]])

# Create another tensor B
B = tf.constant([[7, 8],
                 [4, 5]])

print(V)
B

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[3, 1],
       [5, 2]])>


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[7, 8],
       [4, 5]])>

In [4]:
# Concatenate columns
AB_concatenated = tf.concat(values=[A, B], axis=1)
AB_concatenated

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[4, 3, 7, 8],
       [6, 1, 4, 5]])>

In [5]:
# Concatenate rows
AB_concatenated = tf.concat(values=[A, B], axis=0)
AB_concatenated

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[4, 3],
       [6, 1],
       [7, 8],
       [4, 5]])>

In [6]:
tensor_z = tf.zeros(shape=[3,4], dtype=tf.float32)
tensor_o = tf.ones(shape=[3,4], dtype=tf.float32)
tensor_r = tf.random.uniform(shape=[3,4], dtype=tf.float32)
tensor_r

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0.39223146, 0.97230434, 0.8170537 , 0.6977552 ],
       [0.9846246 , 0.22668004, 0.71496   , 0.9319242 ],
       [0.48455083, 0.44268644, 0.1193794 , 0.21394587]], dtype=float32)>

In [7]:
reshaped_tensor = tf.reshape(tensor = tensor_r,
                             shape = [4, 3])
reshaped_tensor

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[0.39223146, 0.97230434, 0.8170537 ],
       [0.6977552 , 0.9846246 , 0.22668004],
       [0.71496   , 0.9319242 , 0.48455083],
       [0.44268644, 0.1193794 , 0.21394587]], dtype=float32)>

In [8]:
# Typecast a tensor
tensor = tf.constant([[4.5, 4.2],
                      [7.5, 3.6],
                      [2.7, 9.4],
                      [6.7, 8.3]],
                      dtype=tf.float32)
tensor_as_int = tf.cast(tensor, tf.int32)
print(tensor)
print(tensor_as_int)

tf.Tensor(
[[4.5 4.2]
 [7.5 3.6]
 [2.7 9.4]
 [6.7 8.3]], shape=(4, 2), dtype=float32)
tf.Tensor(
[[4 4]
 [7 3]
 [2 9]
 [6 8]], shape=(4, 2), dtype=int32)


In [9]:
a = tf.transpose(tensor_as_int)
a

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[4, 7, 2, 6],
       [4, 3, 9, 8]])>

In [10]:
# Matrix multiplication of tensors
A = tf.constant([[5, 8],
                 [3, 9]])

# Some vecotr v
v = tf.constant([[4],
                 [2]])

Av = tf.matmul(A,v)
Av

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[36],
       [30]])>

In [11]:
# Element-wise multiplication
Av = tf.multiply(A,v)
Av

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 32],
       [ 6, 18]])>

In [12]:
# Creating an identity matrix

A = tf.constant([[4, 9],
                 [5, 6],
                 [1, 8]])
rows, columns = A.shape
print('rows:', rows, 'columns:', columns)

# Making identity matrix
A_identity = tf.eye(num_rows = rows,
                    num_columns = columns,
                    dtype = tf.int32)
A_identity

rows: 3 columns: 2


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 0],
       [0, 1],
       [0, 0]])>

IndexError: tuple index out of range

In [16]:
tensor

<tf.Tensor: shape=(4, 2), dtype=float32, numpy=
array([[4.5, 4.2],
       [7.5, 3.6],
       [2.7, 9.4],
       [6.7, 8.3]], dtype=float32)>